api_platform:
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        max_joins: 1
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        json: ['application/json']
        html: ['text/html']
    collection:
        pagination:
            enabled: true
            partial: false
            client_items_per_page: true